### ISSUE TITLE
Could you add my project to Library Usage section in your README?

### ISSUE THREAD

**Issue by jeongmin** [grafov/m3u8#101]
Hello grafov.

I've made an webpage that showing m3u8 format of URL which user inserted. It is built on your parser. If you don't mind, could you add my project to Library Usage section in your README?

It would be honor to me! :)

Here is the my project link and screenshot.

https://github.com/jeongmin/m3u8-reader

![Screenshot of HLS READER](https://github.com/jeongmin/hls-reader/blob/master/screenshot.png?raw=true)

**Comment by bradleyfalzon** [comment]
I don't see a problem with this, are you able to provide a PR?

**Comment by jeongmin** [comment]
I created pull request about this. Thanks! :)
