### ISSUE TITLE
Support to EXT-X-INDEPENDENT-SEGMENTS in Go Lib

### ISSUE THREAD

**Issue by alessandrojp** [grafov/m3u8#103]
Hi,

I would like to know if there is any plan for supporting `EXT-X-INDEPENDENT-SEGMENTS`  in the Go Lib?

Thank you.

**Comment by zanes2016** [comment]
Support for `EXT-X-INDEPENDENT-SEGMENTS` was introduced in `VERSION: 6`. Currently only version 5 is supported. I agree, it would be helpful to add support for the latest versions (6 & 7).

**Comment by bradleyfalzon** [comment]
There's no planned support, if there's particular features you require we can look at them and possibly implement them - but most support has been added on an as-needed basis and usually via contributed PRs.

Is `EXT-X-INDEPENDENT-SEGMENTS` something you'd be willing to PR and iterate on?

**Comment by bradleyfalzon** [comment]
Looking at https://tools.ietf.org/html/rfc8216#section-4.3.5.1

It seems to be a pretty straight forward `bool` on the master playlist, with reader and writer support along with some appropriate tests.

Is this something you'd be willing to start?

**Comment by leikao** [comment]
The `EXT-X-INDEPENDENT-SEGMENTS` is supported by #128 , so close this issue.
