### ISSUE TITLE
SeqId is not set when parsing media playlist

### ISSUE THREAD

**Issue by thinkski** [grafov/m3u8#107]
Upon decoding a media playlist, I expected `SeqId` of each segment to contain the sequence id of each segment. For example, if `SeqNo` of the playlist were 123 and it had three segments, I would expect the `SeqId` of the three segments to be 123, 124, and 125. However, they are all 0, regardless of `SeqNo`.

My current workaround it to populate the sequence ids after the fact myself:
```
pls, listType, err := m3u8.DecodeFrom(reader, true)

switch listType {
    case m3u8.MEDIA:
        // Cast to media playlist type
        mediapls := pls.(*m3u8.MediaPlaylist)

        // Populate segment sequence id from playlist sequence number
        for i, segment := range mediapls.Segments {
            if segment == nil {
                break
            }
            mediapls.Segments[i].SeqId = mediapls.SeqNo + uint64(i)
        }
        ...
```

**Comment by leikao** [comment]
dup of #116

**Comment by thinkski** [comment]
I would say the later issue is a duplicate of the earlier issue 😉 But glad to see the `SeqId` issue is being addressed.

**Comment by leikao** [comment]
@thinkski I made a PR #124 to solve this issue, welcome to try it.
