### ISSUE TITLE
MediaSegment@SeqId should be the media sequence of an individual segment?

### ISSUE THREAD

**Issue by leandromoreira** [grafov/m3u8#116]
Each [sub manifest has its initial (media) sequence number](https://github.com/grafov/m3u8/blob/master/structure.go#L104) and I was under the impression that the attribute `SeqId` from the `MediaSegment` was the individual media sequence for that segment, am I right?

Also, I was browsing through the [docs](https://gowalker.org/github.com/grafov/m3u8#MediaSegment) and also the source code and I couldn't find where the attribute `SeqId` is filled.

**Comment by leandromoreira** [comment]
By the way, why did you pick `SeqNo` as `uint64`?

I think the type `int64` might be enough, even if you pick an `int32` type and a user sets each segment about `1s` we would work for 70 years without wraparound.

**Comment by leikao** [comment]
> By the way, why did you pick `SeqNo` as `uint64`?

Hi @leandromoreira , [RFC 8216](https://tools.ietf.org/html/rfc8216#section-4.3.3.1) defines the data type of `SeqNo`, the value range of *decimal-integer* is [defined here](https://tools.ietf.org/html/rfc8216#section-4.2).

    o  decimal-integer: an unquoted string of characters from the set
       [0..9] expressing an integer in base-10 arithmetic in the range
       from 0 to 2^64-1 (18446744073709551615).  A decimal-integer may be
       from 1 to 20 characters long.

**Comment by leandromoreira** [comment]
Thanks @leikao do you know why `SeqId` is not being set?

**Comment by leikao** [comment]
> Thanks @leikao do you know why `SeqId` is not being set?

Sorry @leandromoreira I don't know the reason why `SeqId` is not being set, may @grafov can give some points. You are welcome to submit a PR to improve this :)

**Comment by leikao** [comment]
@leandromoreira I made a PR #124 to support `MediaSegment@SeqId`, welcome to try it :)

**Comment by leikao** [comment]
PR #124 solved this issue, close it.
