### ISSUE TITLE
missing new line after #EXT-X-DISCONTINUITY-SEQUENCE

### ISSUE THREAD

**Issue by agparadiso** [grafov/m3u8#130]
Hey! I found that there is a missing new line after the #EXT-X-DISCONTINUITY-SEQUENCE, so when rendering a mediaplaylist with a DiscontinuitySeq different than 0 a new line is missing, so is being displayed as:
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:15150186350000
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY-SEQUENCE:1#EXTINF:2.000,
```
instead of:
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:15150186350000
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY-SEQUENCE:1
#EXTINF:2.000,
```

I've created a [PR](https://github.com/grafov/m3u8/pull/129) fixing this.

**Comment by leikao** [comment]
Thank you @agparadiso .
