### ISSUE TITLE
Under load  encoder does not perform correctly

### ISSUE THREAD

**Issue by agparadiso** [grafov/m3u8#137]
I've created a [PR](https://github.com/grafov/m3u8/pull/136) introducing some tests that simulates "high traffic" and validates the correctness of the playlist.

I've found that under load rendering the playlist as:  MediaPlaylist.String() returns incomplete playlists causing the video to stop playing.

I'll be working on this but would like to know if you run against this issue and any help on fixing it it's also appreciated 💪

**Comment by eric** [comment]
This library isn't threadsafe. If you want to use `MediaPlaylist.String()` from multiple goroutines at the same time, you'll need to use `sync.Mutex`.

**Comment by agparadiso** [comment]
Hi @eric thanks for the response, I'm running `MediaPlaylist.String()` from several goroutines to simulate high traffic, but I'm getting the same behaviour in my project without the use of multiple goroutines.

**Comment by agparadiso** [comment]
I found out a way to fix it. I was creating a new MediaPlaylist and returning a pointer to it in a function like this:
`RenderVariantPlaylist(metadata *metadata.Variation) (m3u8.MediaPlaylist, error)`
and outside this function I was calling MediaPlaylist.String(). 

under load it was generating some weird playlist. I fix it by returning a string and doing the mediaPlaylist.String() inside the RenderVariantPlaylist function.
