### ISSUE TITLE
Support for (non standard) Name attribute in #EXT-X-STREAM-INF tag

### ISSUE THREAD

**Issue by bradleyfalzon** [grafov/m3u8#29]
Hi,

I've begun using this extension for some manifest file manipulation, but come across a small issue where I'm using a non standard extension within the HLS spec that's been implemented by Wowza and JWPlayer.

The functionality adds an extra parameter to `#EXT-X-STREAM-INF` called `Name` which is added by Wowza and used by JWPlayer to show a more useful name for the variant in a client's quality selector. See http://support.jwplayer.com/customer/portal/articles/1430240-hls-adaptive-streaming

Note this shouldn't be confused with `Name` in the `#EXT-X-MEDIA`.

Would you accept an PR to add this functionality? It would add a `Name` field added to `VariantParams` struct (similar to the same tag in Alternative struct), additional support in `decodeLineOfMasterPlaylist` and `(p *MasterPlaylist) Encode`, along with corresponding tests, and sample-playlist.

Sample playlist:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1828000,NAME="4 high",RESOLUTION=896x504
chunklist_b1828000_t64NCBoaWdo.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1378000,NAME="3 med",RESOLUTION=768x432
chunklist_b1378000_t64MyBtZWQ=.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=678000,NAME="2 med",RESOLUTION=512x288
chunklist_b678000_t64MiBtZWQ=.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=438000,NAME="1 low",RESOLUTION=384x216
chunklist_b438000_t64MSBsb3c=.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=128000,NAME="0 audio"
chunklist_b128000_t64MCBhdWRpbw==.m3u8
```

**Comment by grafov** [comment]
Library already supports nonstandard tags from Widevine so one another nonstandard parameter not a problem :) Yes, I will accept such code. Please provide it with a sample playlist and unit test.

It seems like a `NAME` parameter was introduced in `#EXT-X-MEDIA` tag and it is a right way to name alternative streams. But Wowza supports it in `#EXT-X-STREAM-INF` along with obsoleted in proto 6 `PROGRAM-ID` parameter.

**Comment by bradleyfalzon** [comment]
Please see above PR, I've added the extra Name attribute, but I've also been considering using a map[string]string in the `Variant` struct (perhaps called Extra) to store other unknown attributes - this map method may help being forward compatible, but I'm on the fence on this...

**Comment by bradleyfalzon** [comment]
New release works well, thanks.
