### ISSUE TITLE
Why replace seqNo 0 to 1?

### ISSUE THREAD

**Issue by hori-ryota** [grafov/m3u8#37]
I think `#EXT-X-MEDIA-SEQUENCE` value is allowed `0` (example: [Technical Note TN2288: Example Playlist Files for use with HTTP Live Streaming](https://developer.apple.com/library/ios/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-TNTAG2)), but `0` is replaced now. Why?

[m3u8/writer.go at master · grafov/m3u8](https://github.com/grafov/m3u8/blob/master/writer.go#L313-L315)

**Comment by bradleyfalzon** [comment]
We had been discussing this today, and don't completely understand why it was introduced in b5ae3cda1ea04cffde8f2b0953c196830014fbd9.

Note, we don't have an issue with this (right now at least) in live or VoD, it's just strange to see.

**Comment by hori-ryota** [comment]
My project use hls live streaming starting from 0 SeqNo.
We decode our original playlist and processed it with this library.

Now, this library encode like followings at first chunk.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:2.0,
0.ts
#EXTINF:2.0,
1.ts
#EXTINF:2.0,
2.ts
```
And next, 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:2.0,
1.ts
#EXTINF:2.0,
2.ts
#EXTINF:2.0,
3.ts
```

This stream is broken because SeqNo is not changed.
Player cannot playback.

Will you make modifications without a disadvantage?
