### ISSUE TITLE
m3u8.DecodeFrom create playlistMedia with 1024 Segments

### ISSUE THREAD

**Issue by vany-egorov** [grafov/m3u8#5]
https://github.com/grafov/m3u8/blob/master/reader.go#L151

I have mediaPlaylistFile with 1203 segments (c_00000000.ts - c_00001202.ts).
But when I do: **m3u8.DecodeFrom** I got **len(playlistMedia.Segments)** == **1024**!:

    playlistFile, _ := os.Open(pathToMediaPlaylistFile)
    defer playlistFile.Close()
    playlist, listType, _ = m3u8.DecodeFrom(bufio.NewReader(playlistFile), true)
    switch listType {
    case m3u8.MEDIA:
        playlistMedia := playlist.(*m3u8.MediaPlaylist)
        fmt.Printf("%d\n", len(playlistMedia.Segments))
    }

How can I iterate over more than 1024 segments?
How can I get total duration?
How can I get full URI slice?

**Comment by iivarih** [comment]
This really is an issue... l

Also len(Segments) == 1024 when you only have ie. 3 segments... so in for-range loop you need to check nil values...

**Comment by barake** [comment]
MediaPlaylist.Segments is a slice. DecodeFrom auto-initializes the slice to a length of 1024: https://github.com/grafov/m3u8/blob/master/reader.go#L154

Instead use MediaPlaylist.Count method to get the current number of segments in the playlist. See https://github.com/grafov/m3u8/blob/master/writer.go#L504

**Comment by chobits** [comment]
I have the same question.
There are `head`, `tail` and `count` private fields of `MediaPlaylist` structure,  but only `count` field is exported via `MediaPlaylist.Count()` method.

**Comment by bradleyfalzon** [comment]
If there's additional APIs people want, let me know and I should be able to implement. We've had similar requirements, but using `.Count()` methods has been fine for us (if the issue is only `len(Segments)`).

**Comment by bradleyfalzon** [comment]
#70 adds the ability for playlist to auto extend beyond 1024 segments and exposes winsize.
