### ISSUE TITLE
if EXT-X-KEY Method is NONE, URI must be skipped.

### ISSUE THREAD

**Issue by miyaji27** [grafov/m3u8#68]
from HLS draft,
https://tools.ietf.org/html/draft-pantos-http-live-streaming-13#section-3.4.4

>    An encryption method of NONE means that media segments are not
>    encrypted.  If the encryption method is NONE, the following
>    attributes MUST NOT be present: URI; IV; KEYFORMAT;
>    KEYFORMATVERSIONS.

**Comment by bradleyfalzon** [comment]
Hi @miyaji27, can you add some extra context around this quote? Is m3u8 doing something it shouldn't, if so, what is it doing? This will help us address the actual issue you might be having.

**Comment by miyaji27** [comment]
I want to combine two ts chunck list, one is AES encrypted, and other one is not encrypted.
But this `writer.go` does not care the condition that #EXT-X-KEY method is NONE.

I already wrote the patch code, PR is here. Please check my PR.
https://github.com/grafov/m3u8/pull/69

**Comment by bradleyfalzon** [comment]
Fixed in #95.
