### ISSUE TITLE
Question: Custom TAGs

### ISSUE THREAD

**Issue by md2k** [grafov/m3u8#82]
Hi @grafov , i not sure maybe i overlooked, but do we have support of custom TAGs, for example it can be handy for implementation of custom DRM like system.

Thanks in advance.

**Comment by grafov** [comment]
No, you are not overlooked, the library doesn't support custom tags. I didn't think about such level of flexibility. If think about realization of such feature it would look like a handler function that accepts playlist type (master or mediaa), token name and value. So when parser meets an unknown tag it calls this function.

**Comment by HazCod** [comment]
Would this mean the parsing of `tvg-*` tags?

```
#EXTINF:-1 tvg-id="Nat Geo HD BE" tvg-name="National Geographic HD BE" tvg-logo="http://picon.space/nationalgeographichd.png" group-title="group",National Geographic HD BE
```

**Comment by bradleyfalzon** [comment]
Yeah, with something like what I proposed in https://github.com/grafov/m3u8/pull/83#issuecomment-298267652 should do that.

**Comment by xybydy** [comment]
I am not sure if I should create pull request since I didn't tested it comprehensively but I have implemented custom tags support on my fork.

**Comment by xybydy** [comment]
I am not sure if I should create a pull request since I didn't test it comprehensively but I have implemented custom tags support on my fork.
