### ISSUE TITLE
No duration when EXTINF without comma in the end

### ISSUE THREAD

**Issue by igk1972** [grafov/m3u8#84]
@bradleyfalzon @grafov 

Problem: 
No parse duration segments.

Some m3u8 include EXTINF without comma in end.
Example:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXTINF:10.000
c_1267327549363093.ts
#EXTINF:10.000
c_1267327549363094.ts
#EXTINF:10.000
c_1267327549363095.ts
```

Solution:
Need revert [this break](https://github.com/grafov/m3u8/blob/master/reader.go#L361) with:
`sepIndex = len(line)`

**Comment by grafov** [comment]
For sure are you about comma in the end?

**Comment by grafov** [comment]
It looks like these playlists don't support standard. So then it is not a bug but a feature for the library - support broken playlists. I think support of these broken playlists will not affect valid playlists so we can add this "feature". What do you think @bradleyfalzon?

**Comment by igk1972** [comment]
@grafov 
I was wrong, of course it's a comma

**Comment by bradleyfalzon** [comment]
I agree @grafov, it seems safe to be a little less strict. Something like:

```diff
diff --git a/reader.go b/reader.go
index cabe0a8..7f035ea 100644
--- a/reader.go
+++ b/reader.go
@@ -358,7 +358,10 @@ func decodeLineOfMediaPlaylist(p *MediaPlaylist, wv *WV, state *decodingState, l
                state.listType = MEDIA
                sepIndex := strings.Index(line, ",")
                if sepIndex == -1 {
-                       break
+                       if strict {
+                               return fmt.Errorf("could not parse: %q", line)
+                       }
+                       sepIndex = len(line)
                }
                duration := line[8:sepIndex]
                if len(duration) > 0 {
```

This will now error when in strict mode instead of silently discarding the EXTINF duration, and allows the user to switch to a non-strict parsing to accept the bad input.

**Comment by bradleyfalzon** [comment]
OK, checked out #85 and see if that's suitable.
